common/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from . import views

app_name = 'common'

urlpatterns = [
    path('login/', auth_views.LoginView.as_view(
        template_name = 'common/login.html'
    ), name='login'),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),
    path('signup/', views.signup, name='signup'),
]

config/urls.py
from django.contrib import admin
from django.urls import path, include
from crud import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('crud/', include('crud.urls')),
    path('common/', include('common.urls')),
    path('', views.index, name='index'),
]

crud/urls.py
from django.urls import path
from . import views

app_name = 'crud'

urlpatterns = [
    path('', views.index, name = 'index'),
    path('<int:board_id>/', views.detail, name='detail'),
    path('board/create/', views.board_create, name='board_create'),
    path('board/modify/<int:board_id>/', views.board_modify, name='board_modify'),
    path('board/delete/<int:board_id>/', views.board_delete, name='board_delete'),
]

common/models.py
from django.db import models

# Create your models here.

crud/models.py
from django.db import models

# Create your models here.
from django.contrib.auth.models import User
from django.db import models

class Board(models.Model):
    author = models.ForeignKey(User, on_delete=models.CASCADE)
    subject = models.CharField(max_length=200)
    content = models.TextField()
    create_date = models.DateTimeField()
    modify_date = models.DateTimeField(null=True, blank=True)

common/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User

class UserForm(UserCreationForm):
    email = forms.EmailField(label="이메일")

    class Meta:
        model = User
        fields = ("username", "email")

crud/forms.py
from django import forms
from crud.models import Board

class BoardForm(forms.ModelForm):
    class Meta:
        model = Board
        fields = ['subject', 'content']

common/views.py
from django.shortcuts import render

# Create your views here.

from django.contrib.auth import authenticate, login
from django.shortcuts import render, redirect
from .forms import UserForm

def signup(request):
    # 회원가입
    if request.method == "POST":
        form = UserForm(request.POST)
        if form.is_valid():
            form.save()
            username = form.cleaned_date.get("username")
            raw_password = form.cleaned_date.get("password1")
            user = authenticate(username=username, password=raw_password)
            login(request, user)
            return redirect('index')
    else:
        form = UserForm()
    return render(request, 'common/signup.html', {'form':form})

crud/views.py
from django.core.paginator import Paginator
from django.utils import timezone
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth.decorators import login_required
from django.contrib import messages
# Create your views here.

from django.http import HttpResponse
from .models import Board
from .forms import BoardForm

def index(request):
    # 게시판 목록 출력하기
    page = request.GET.get('page', '1') # 페이지

    board_list = Board.objects.order_by('-create_date')

    # 페이징 처리
    paginator = Paginator(board_list, 10)
    page_obj = paginator.get_page(page)

    context = {'board_list' : page_obj}

    return render(request, 'crud/board_list.html', context)

def detail(request, board_id):
    # 게시판 조회
    board = Board.objects.get(id=board_id)
    context = {'board':board}
    return render(request, 'crud/board_detail.html', context)

@login_required(login_url='common:login')
def board_create(request):
    # 게시판 생성
    if request.method == 'POST':
        form = BoardForm(request.POST)
        if form.is_valid():
            board = form.save(commit=False)
            board.author = request.user
            board.create_date = timezone.now()
            board.save()
            return redirect('crud:index')
    else:
        form = BoardForm()
    context = {'form':form}
    return render(request, 'crud/board_form.html', context)

@login_required(login_url='common:login')
def board_modify(request, board_id):
    # 게시판 수정
    board = get_object_or_404(Board, pk=board_id)
    if request.user != board.author:
        messages.error(request, '수정권한이 없어요 ㅠ,ㅠ')
        return redirect('crud:detail', board_id=board.id)
    if request.method == "POST":
        form = BoardForm(request.POST, instance=board)
        if form.is_valid():
            board = form.save(commit=False)
            board.author = request.user
            board.modify_date = timezone.now()
            board.save()
            return redirect('crud:detail', board_id=board.id)
    else:
        form = BoardForm(instance=board)
    context = {'form' : form}
    return render(request, 'crud/board_form.html', context)

@login_required(login_url='common:login')
def board_delete(request, board_id):
    # 게시판 삭제
    board = get_object_or_404(Board, pk=board_id)
    if request.user != board.author:
        messages.error(request, '삭제권한이 없어요 ㅠ,ㅠ')
        return render('crud:detail', board_id=board.id)
    board.delete()
    return redirect('crud:index')

templates/base.html
{% load static %}
<!doctype html>
<html lang="ko">
<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <!-- Bootstrap CSS -->
    <link rel="stylesheet" type="text/css" href="{% static 'bootstrap.min.css' %}">
    <!-- pybo CSS -->
    <link rel="stylesheet" type="text/css" href="{% static 'style.css' %}">
    <title>프리온딩 백엔드 코스 | 장현호</title>
</head>
<body>
{% include "navbar.html" %}
<!-- 기본 템플릿 안에 삽입될 내용 Start -->
{% block content %}
{% endblock %}
<!-- 기본 템플릿 안에 삽입될 내용 End -->
<<!-- jQuery JS -->
<script src="{% static 'jquery-3.4.1.min.js' %}"></script>
<!-- Bootstrap JS -->
<script src="{% static 'bootstrap.min.js' %}"></script>

</body>
</html>

templates/common/login.html
{% extends "base.html" %}
{% block content %}
<div class="container my-3">
    <div class="row">
        <div class="col-4">
            <h4>로그인</h4>
        </div>
        <div class="col-8 text-right">
            <span>또는 <a href="{% url 'common:signup' %}">계정을 만드세요.</a></span>
        </div>
    </div>
    <form method="post" class="post-form" action="{% url 'common:login' %}">
        {% csrf_token %}
        <input type="hidden" name="next" value="{{ next }}">  <!-- 로그인 성공후 이동되는 URL -->
        {% include "form_errors.html" %}
        <div class="form-group">
            <label for="username">사용자ID</label>
            <input type="text" class="form-control" name="username" id="username"
                   value="{{ form.username.value|default_if_none:'' }}">
        </div>
        <div class="form-group">
            <label for="password">비밀번호</label>
            <input type="password" class="form-control" name="password" id="password"
                   value="{{ form.password.value|default_if_none:'' }}">
        </div>
        <button type="submit" class="btn btn-primary">로그인</button>
    </form>
</div>
{% endblock %}

templates/common/signup.html
{% extends "base.html" %}
{% block content %}
<div class="container my-3">
    <div class="row my-3">
        <div class="col-4">
            <h4>계정생성</h4>
        </div>
        <div class="col-8 text-right">
            <span>또는 <a href="{% url 'common:login' %}">로그인 하세요.</a></span>
        </div>
    </div>
    <form method="post" class="post-form">
        {% csrf_token %}
        {% include "form_errors.html" %}
        <div class="form-group">
            <label for="username">사용자 이름</label>
            <input type="text" class="form-control" name="username" id="username"
                   value="{{ form.username.value|default_if_none:'' }}">
        </div>
        <div class="form-group">
            <label for="password1">비밀번호</label>
            <input type="password" class="form-control" name="password1" id="password1"
                   value="{{ form.password1.value|default_if_none:'' }}">
        </div>
        <div class="form-group">
            <label for="password2">비밀번호 확인</label>
            <input type="password" class="form-control" name="password2" id="password2"
                   value="{{ form.password2.value|default_if_none:'' }}">
        </div>
        <div class="form-group">
            <label for="email">이메일</label>
            <input type="text" class="form-control" name="email" id="email"
                   value="{{ form.email.value|default_if_none:'' }}">
        </div>
        <button type="submit" class="btn btn-primary">생성하기</button>
    </form>
</div>
{% endblock %}
© 2021 GitHub, Inc.
Terms
P

templates/crud/board_detail.html
{% extends 'base.html' %}
{% block content %}
<h1>제목 : {{board.subject}}</h1>
<h2>작성자 : {{board.author.username}}</h2>
<div>
    내용 : {{board.content}}
</div>
<hr>
{% if request.user == board.author %}
<div>
    <a href="{% url 'crud:board_modify' board.id %}">수정하기</a>
    <a href="{% url 'crud:board_delete' board.id %}">삭제하기</a>
</div>
{% endif %}
{% endblock %}

templates/crud/board_form.html
{% extends 'base.html' %}

{% block content %}
<div>
    <h5>게시글 생성</h5>
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">저장하기</button>
    </form>
</div>
{% endblock %}

templates/crud/board_list.html
{% extends 'base.html' %}
{% block content %}
<div class="container my-3">
    <table class = "table">
        <thead>
        <tr class="thread-dark">
            <th>번호</th>
            <th style="width:50%">제목</th>
            <th>글쓴이</th>
            <th>작성일시</th>
        </tr>
        </thead>
        <tbody>
        {% if board_list %}
        {% for board in board_list %}
        <tr class="text-center">
            <td>{{forloop.counter}}</td>
            <td class="text-left">
                <a href="{% url 'crud:detail' board.id %}">
                    {{ board.subject }}
                </a>
            </td>
            <td>{{board.author.username}}</td>
            <td>{{board.create_date}}</td>
        </tr>
        {% endfor %}
        {% else %}
        <tr>
            <td colspan="3">질문이 없습니다.</td>
        </tr>
        {% endif %}
        </tbody>
    </table>
</div>

<!-- 페이징처리 -->
{% if board_list.has_previous %}
<a href="?page={{board_list.previous_page_number}}">이전으로</a>
{% endif %}
<span>{{board_list.number}}</span>
<span>/</span>
<span>{{board_list.paginator.num_pages}}</span>
{% if board_list.has_next %}
<a href="?page={{board_list.next_page_number}}">다음으로</a>
{% endif %}


<br>
<a href="{% url 'crud:board_create' %}">게시글 만들기 :)</a>
{% endblock %}

templates/form_errors.html
{% if form.errors %}
    {% for field in form %}
        {% for error in field.errors %}
            <div class="alert alert-danger">
                <strong>{{ field.label }}</strong>
                {{ error }}
            </div>
        {% endfor %}
    {% endfor %}
    {% for error in form.non_field_errors %}
        <div class="alert alert-danger">
            <strong>{{ error }}</strong>
        </div>
    {% endfor %}
{% endif %}

templates/navbar.html
<h1>
    {% if user.is_authenticated %}
    <a href="{% url 'common:logout' %}">
        {{ user.username }} ❌ 로그아웃
    </a>
    {% else %}
    <a href="{% url 'common:login' %}">로그인</a>
    {% endif %}
</h1>